### ISSUE TITLE
Bug: 各种包装类型零值问题

### ISSUE THREAD

**Issue by dajiiu** [apache/dubbo-go-hessian2#100]
**What happened**:
**主要问题：Integer类型null转golang中的int类型报错**
---  
*可能会出现的其他问题：*
基础包装类型0值都可能出现无法接收的情况
基本类型                  包装类型
Byte
**Integer null值**  
Short
Long
Float
Double
Boolean
Character
**String null值**

**How to reproduce it (as minimally and precisely as possible)**:
在golang中专门设置一套可以接收0值得基础类型

**Anything else we need to know?**:
对于java中的复杂类型，golang接收或多或少会出现一些问题。要么不能接收，要么部分接收(如Date类型null值不能被golang中的time.Time接收)

**Comment by AlexStocks** [comment]
@pepigo maybe u should give us some test cases.

**Comment by pepigo** [comment]
**Integer类型的null问题**
> 我已经使用官方的demo测试出问题了，确实不能接收

![image](https://user-images.githubusercontent.com/52339367/61443096-690c5c00-a97b-11e9-8a84-c9466a9aa650.png)

**Comment by pepigo** [comment]
### dubbo-go类型对应关系

| java-server | go-client | description1 | description2 |
| :---------: | :-------: | :---------: | :---------: |
| Byte |    byte       | 使用string可以接收null值 | byte可接收正常数据 |
| Short | int16 | 使用string可以接收null值 | int16可接收正常数据 |
| Integer | int32 | 使用string可以接收null值 | int32可接收正常数据 |
| Long | int64 | 使用string可以接收null值 | int64可接收正常数据 |
| Float | float32 | 使用string可以接收null值 | float32可接收正常数据 |
| Double | float64 | 使用string可以接收null值 | float64可接收正常数据 |
| Boolean | bool | 使用string可以接收null值 | bool可接收正常数据 |
| Character | string | 使用string接收可以接收null值 | java Character只能使用golang string接收 |

**Comment by pepigo** [comment]
**类型接收测试结果：**

**Comment by wongoo** [comment]
@pepigo I don't think it's a good idea to add more `**basic data type**` mapping , which is out of the scope of hessian serialization protocol.  Another data type like BigDecimal, which is used widely in business and no solution for it, then we consider to support it.   see https://github.com/hessian-group/hessian-type-mapping

**Comment by wongoo** [comment]
close for it's not urgent now
