### ISSUE TITLE
decode时，忽略go结构不存在字段。

### ISSUE THREAD

**Issue by pantianying** [apache/dubbo-go-hessian2#101]
**What would you like to be added**:
     目前只能decode和hessian.RegisterPOJO注入的结构完全一致的字段，如果java bean多字段就会报错。
    希望可以忽略无法匹配的字段，与json序列化使用方式保持一致。
*Why is this needed**:
     java服务升级时经常会改动（特别是增加）bean的属性字段，目前的状况是go必须同样升级，这样显然是难以接受的。

**Comment by wongoo** [comment]
@pantianying A important question, should we avoid fields if it's not exists for hessian? I think protocol buffer do not.  If it's not used, delete it.  

Json is a special serializer and not caring data compacting， while hessian is a binary serializer, remove unused data, keep it efficient. 

@AlexStocks @aliiohs what's your opinion?

**Comment by AlexStocks** [comment]
@wongoo agree with u.

**Comment by wongoo** [comment]
It's impossible to skip unregistered field for hessian.
