### ISSUE TITLE
多级指针反序列化bug

### ISSUE THREAD

**Issue by aliiohs** [apache/dubbo-go-hessian2#106]
**What happened**:
type Demo{
     Name ***string
}
当目标为多级指针时会出现序列化错误，当前已暂时修复部分类型。具体解决方案未出。
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by wongoo** [comment]
@aliiohs @AlexStocks  I think multi-level pointer should be forbidden, which can be checked when registering POJO.

**Comment by AlexStocks** [comment]
@wongoo agree with u
