### ISSUE TITLE
decode failed when invoke to java server ,and return specially

### ISSUE THREAD

**Issue by pantianying** [apache/dubbo-go-hessian2#116]
**What happened**:
![image](https://user-images.githubusercontent.com/20589945/62672977-37f9d700-b9cf-11e9-869d-2dddf1b40644.png)

decode failed when invoke to java server ,and return specially
success for only JSONObject,success for only JSONArray
but fail with both JSONObject and  JSONArray

**What you expected to happen**:
fix this bug 
**How to reproduce it (as minimally and precisely as possible)**:

this is the demo to Reproduction problem: 
hessainTest in
https://github.com/pantianying/dubbo-go/blob/hessain_decode_fail/examples/general/dubbo/go-client/app/client.go

getTest in
https://github.com/pantianying/dubbo-go/blob/hessain_decode_fail/examples/general/dubbo/java-server/src/main/java/com/ikurento/user/UserProviderImpl.java
 

**Anything else we need to know?**:
this is hessain log:
![image](https://user-images.githubusercontent.com/20589945/62673213-1cdb9700-b9d0-11e9-94f7-559d04eeafab.png)

**Comment by wongoo** [comment]
@pantianying have you try HashMap instead of JSONObject, try ArrayList instead of JSONArray?

**Comment by pantianying** [comment]
> @pantianying have you try HashMap instead of JSONObject, try ArrayList instead of JSONArray?
I am not do that,but I try Object instead of JSONObject and JSONArray ,also has problems。Oddly enough, there's no problem with just one of them. (see my code annotation in java)

**Comment by wongoo** [comment]
@pantianying it's difficult to run your example, instead you can provide a simple unit test for that, it will be better to find bugs , see https://github.com/apache/dubbo-go-hessian2/blob/177b9c667283b33219ce8ab5886926cb931bf0b1/decode_test.go#L87
