### ISSUE TITLE
关于map的解析

### ISSUE THREAD

**Issue by fangyincheng** [apache/dubbo-go-hessian2#119]
**What happened**:

hessian的map解析有两种情况，`typed`和`untyped`，问题出在`typed`的情况。如图：红框所在发生`illegal class index @idx %d`错误
![image](https://user-images.githubusercontent.com/18375310/63648320-da9cae80-c760-11e9-9139-b03a9677a4fb.png)

**What you expected to happen**:

调试之后发现，在第一次得到某个`type`的时候（如图1：），如果不存在该类型会使用untyped方式继续解析map内容（如图2）。但是如果是map有嵌套或者数组情况，会导致能解析第一个，但是第二个开始就找不到index对应的类型了。如果支持typed map，我们是否应该限制必须注册类型，而不是默认处理为untyped。
![image](https://user-images.githubusercontent.com/18375310/63648353-3d8e4580-c761-11e9-9911-5e63854311cc.png)
图1
![image](https://user-images.githubusercontent.com/18375310/63648385-a4136380-c761-11e9-950d-4aa4a03779bf.png)
图2

**How to reproduce it (as minimally and precisely as possible)**:

重现可以添加如下的java测试代码：
![image](https://user-images.githubusercontent.com/18375310/63648434-54816780-c762-11e9-8131-396eb621a6fb.png)

**Anything else we need to know?**:
另外，下图应该是一个bug，`TAG_READ`应该换为变量`tag`：
![image](https://user-images.githubusercontent.com/18375310/63648406-ea68c280-c761-11e9-9681-d85db09d4e28.png)

**Comment by wongoo** [comment]
@fangyincheng  can you provide a unit test for it?

**Comment by wongoo** [comment]
@fangyincheng  is it already resolved？
