### ISSUE TITLE
Add:  mapping go *bool to java Boolean

### ISSUE THREAD

**Issue by wongoo** [apache/dubbo-go-hessian2#123]
**What would you like to be added**:
mapping go `*bool` to java `Boolean` 
- codec support between java `Boolean` null and go `*bool` nil

**Why is this needed**:
- `Boolean` is used widely in java

**Comment by gaoxinge** [comment]
@wongoo Why not map a `struct` to `Boolean`? `Boolean` is a class in java, so I prefer to defining a bool struct instead of a bool pointer.

**Comment by wongoo** [comment]
> @wongoo Why not map a `struct` to `Boolean`? `Boolean` is a class in java, so I prefer to defining a bool struct instead of a bool pointer.

discuss in community group

**Comment by wongoo** [comment]
close for no requirement
