### ISSUE TITLE
fix:go emoji to java emoji（a character takes up 3-4 bytes of special symbols）

### ISSUE THREAD

**Issue by pantianying** [apache/dubbo-go-hessian2#129]
**What would you like to be added**:

**Why is this needed**:
![image](https://user-images.githubusercontent.com/20589945/64339998-be79f680-d017-11e9-9765-1229d981dfee.png)

**Comment by wongoo** [comment]
@pantianying  pls provide a unit test so that we can follow up

**Comment by pantianying** [comment]
> @pantianying pls provide a unit test so that we can follow up

https://github.com/pantianying/dubbo-go-hessian2/blob/51e52527f9a1e2e2edb41cc873c1cc591fa96de8/string_test.go#L144

**Comment by pantianying** [comment]
ps：
1. Java returns the string of emoji, and the go side will scramble.

2. If Java returns Emoji in a complex map structure, the whole serialization will fail.

3. go coded emoji, Java can not receive.

**Comment by wongoo** [comment]
@pantianying  I find that java uses two 16-bit characters to represent emoji "🤣", while golang uses one rune to represent it.  So the length of the emoji in java is 2, while 1 in java. 

The hessian protocol says that: 
> The length is the number of 16-bit characters.

So, it's a bug of golang hessian2, I will try to fix it.

**Comment by wongoo** [comment]
New knowledge:
1. A char is encoded in UTF-8 format in `com.caucho.hessian.io.Hessian2Output.printString()`
```java
  /**
   * Prints a string to the stream, encoded as UTF-8
   *
   * @param v the string to print.
   */
  public void printString(char []v, int strOffset, int length)
    throws IOException
  {
    int offset = _offset;
    byte []buffer = _buffer;

    for (int i = 0; i < length; i++) {
      if (SIZE <= offset + 16) {
        _offset = offset;
        flushBuffer();
        offset = _offset;
      }

      char ch = v[i + strOffset];

      if (ch < 0x80)
        buffer[offset++] = (byte) (ch);
      else if (ch < 0x800) {
        buffer[offset++] = (byte) (0xc0 + ((ch >> 6) & 0x1f));
        buffer[offset++] = (byte) (0x80 + (ch & 0x3f));
      }
      else {
        buffer[offset++] = (byte) (0xe0 + ((ch >> 12) & 0xf));
        buffer[offset++] = (byte) (0x80 + ((ch >> 6) & 0x3f));
        buffer[offset++] = (byte) (0x80 + (ch & 0x3f));
      }
    }

    _offset = offset;
  }
```

2. A UTF-8 character is decoded in `com.caucho.hessian.io.Hessian2Input.parseUTF8Char()`
```java
  private int parseUTF8Char()
    throws IOException
  {
    int ch = _offset < _length ? (_buffer[_offset++] & 0xff) : read();

    if (ch < 0x80)
      return ch;
    else if ((ch & 0xe0) == 0xc0) {
      int ch1 = read();
      int v = ((ch & 0x1f) << 6) + (ch1 & 0x3f);

      return v;
    }
    else if ((ch & 0xf0) == 0xe0) {
      int ch1 = read();
      int ch2 = read();
      int v = ((ch & 0x0f) << 12) + ((ch1 & 0x3f) << 6) + (ch2 & 0x3f);

      return v;
    }
    else
      throw error("bad utf-8 encoding at " + codeName(ch));
  }
```

**Comment by fangyincheng** [comment]
![image](https://user-images.githubusercontent.com/18375310/64924387-c0616800-d816-11e9-8c80-fefd2a2a0e99.png)

**Comment by wongoo** [comment]
java only support ucs-2, while golang support ucs-4.

**Comment by wongoo** [comment]
i'm working on it, and it may be resolved as early as tomorrow.
