### ISSUE TITLE
1.2.4版本mod 名称错误导致go mod 解析失败

### ISSUE THREAD

**Issue by Jackson-soft** [apache/dubbo-go-hessian2#134]
![image](https://user-images.githubusercontent.com/3928114/66892984-a1c1dd00-f01f-11e9-82b8-d266ffbf17dd.png)

![image](https://user-images.githubusercontent.com/3928114/66893003-a71f2780-f01f-11e9-8ba6-7642beded187.png)

**Comment by wongoo** [comment]
@Jackson-soft  the master branch already fix it, we will release new version asap.
