### ISSUE TITLE
没有找到 java.math.BigInteger 在 golang 中的对应的类型，辛苦支持一下

### ISSUE THREAD

**Issue by fionawp** [apache/dubbo-go-hessian2#140]
**What happened**:
java.math.BigInteger 使用  math/big 的 big.Int， 报错：Last error is client read timeout。希望能够支持一下java.math.BigInteger，谢谢 
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by wongoo** [comment]
see: https://github.com/dubbogo/gost/pull/11

**Comment by wongoo** [comment]
see: https://github.com/apache/dubbo-go-hessian2/pull/141

**Comment by AlexStocks** [comment]
@fionawp bigint has been supported in master branch.
