### ISSUE TITLE
reading github.com/apache/dubbo-go-hessian2/@v/v1.2.4-0.20190807202824-177b9c667283.mod

### ISSUE THREAD

**Issue by arieslee** [apache/dubbo-go-hessian2#143]
无法安装github.com/apache/dubbo-go-hessian2
![image](https://user-images.githubusercontent.com/2550216/70589389-90a1e080-1c0a-11ea-86c5-0fdbcf1d09aa.png)
```go get -u github.com/apache/dubbo-go-hessian2

go: github.com/apache/dubbo-go@v1.1.0 requires
        github.com/apache/dubbo-go-hessian2@v1.2.4-0.20190807202824-177b9c667283: reading https://goproxy.cn/github.com/apache/dubbo-go-hessian2/@v/v1.2.4-0.20190807202824-177b9c667283.mod: 404 Not Found
```

**Comment by wongoo** [comment]
I test it  under the `develop` branch of dubbo-go and there is not error for me. 

try :
```bash
# mac
sed -i "" '/dubbo-go-hessian2/d' go.mod
go get -u github.com/apache/dubbo-go-hessian2
go mod tidy
```

**Comment by arieslee** [comment]
> I test it under the `develop` branch of dubbo-go and there is not error for me.
> 
> try :
> 
> ```shell
> # mac
> sed -i "" '/dubbo-go-hessian2/d' go.mod
> go get -u github.com/apache/dubbo-go-hessian2
> go mod tidy
> ```
And the same question
```
/usr/local/go/bin/go list -m -json all #gosetup
go: github.com/apache/dubbo-go@v0.1.2-0.20190923162929-95f857c89fd2: reading https://goproxy.cn/github.com/apache/dubbo-go/@v/v0.1.2-0.20190923162929-95f857c89fd2.mod: 404 Not Found
```
![image](https://user-images.githubusercontent.com/2550216/70698917-4ea89580-1d03-11ea-8c1c-ee4a4f4846a3.png)

**Comment by wongoo** [comment]
ask for help in community 钉钉群
