### ISSUE TITLE
HessianCodec包头长度检查异常

### ISSUE THREAD

**Issue by witkeysa** [apache/dubbo-go-hessian2#156]
func (h *HessianCodec) ReadHeader(header *DubboHeader) error {

var err error

if h.reader.Size() < HEADER_LENGTH {
	return ErrHeaderNotEnough
}
buf, err := h.reader.Peek(HEADER_LENGTH)
if err != nil { // this is impossible
	return perrors.WithStack(err)
}
...
这一段会检查长度是否大于包头长度。由下面这段调用。
// Unmarshal ...
func (p *DubboPackage) Unmarshal(buf *bytes.Buffer, opts ...interface{}) error {
codec := hessian.NewHessianCodec(bufio.NewReaderSize(buf, buf.Len()))

// read header
err := codec.ReadHeader(&p.Header)
但是在bufio.NewReaderSize(buf, buf.Len())中
func NewReaderSize(rd io.Reader, size int) *Reader {
// Is it already a Reader?
b, ok := rd.(*Reader)
if ok && len(b.buf) >= size {
return b
}
if size < minReadBufferSize {
size = minReadBufferSize
}
r := new(Reader)
r.reset(make([]byte, size), rd)
return r
}
这里创建出的reader长度永远大于16.导致包头分包时，解包异常。

**Comment by Patrick0308** [comment]
你的请求包头是小于16字节的？我看dubbo协议头部都已经大于16了，你收到请求包有问题

**Comment by witkeysa** [comment]
收到的请求包没有问题，但是被分包了，比如说tcp收到的数据长度为200，200这个数据中有一个190长度的包，这个包解包没有问题，但是剩下的10长度的数据会被传到这个函数里解包，然后就会报错，导致这个会话就直接报错退出了

**Comment by AlexStocks** [comment]
@witkeysa what you said is right.

**Comment by AlexStocks** [comment]
@witkeysa I have reopen dubbo-go issue https://github.com/apache/dubbo-go/issues/380 and submit pr https://github.com/apache/dubbo-go/pull/381. so I will close this issue. [sorry Let u close issue 380 before.]
