### ISSUE TITLE
some issues needed to fix for v1.5.0

### ISSUE THREAD

**Issue by wongoo** [apache/dubbo-go-hessian2#177]
**What would you like to be added**:

1. appendix in LICENSE

2. update the dependency libs with them latest version in go.mod:
- github.com/dubbogo/gost v1.8.0
- github.com/pkg/errors v0.9.1
- github.com/stretchr/testify v1.5.1

3. add comment for public struct/functions in
- java_collection.go
- request.go
- serialize.go

**Comment by AlexStocks** [comment]
Compared to the  [license](https://github.com/apache/dubbo-go-hessian2/blob/master/LICENSE) of dubbo-go, the license of this project is lack of the following sentences. What the Mr Justin said "LICENSE is missing the appendix. Please fix this." means that

**Comment by micln** [comment]
something wrong, github.com/stretchr/testify v1.5.1 need Go 1.13+

https://github.com/stretchr/testify/blob/v1.5.1/go.mod#L10

https://travis-ci.org/github/apache/dubbo-go-hessian2/builds/687823542?utm_source=github_status&utm_medium=notification
