### ISSUE TITLE
javaBean返回的字段信息比struct多的时候，无法反序列化

### ISSUE THREAD

**Issue by bobopan** [apache/dubbo-go-hessian2#183]
英文不好，直接中文了

**What would you like to be added**:

golang反序列化的时候struct字段信息支持缺省字段

https://github.com/apache/dubbo-go-hessian2/blob/c4e7f352422864fb76182bfbe8adcaf298d86573/object.go#L342

**Why is this needed**:
golang hessian2反序列化如果struct字段信息比javaBean字段信息少的时候，会出现反序列化失败的错误

**Comment by micln** [comment]
@wongoo does err is necessary ?

**Comment by wongoo** [comment]
> @wongoo does the err is necessary ?

Now hessian2 support ignore fields, but it's not the default behavior. I think it's possible to provide a global setting to allow user to change the default behavior.  

How do you think? @AlexStocks  @fangyincheng @micln @hxmhlt

**Comment by AlexStocks** [comment]
@wongoo agree with u.

**Comment by fangyincheng** [comment]
#201
