### ISSUE TITLE
request 中带枚举类型，在 packRequest 过程中出现 error

### ISSUE THREAD

**Issue by panyfun** [apache/dubbo-go-hessian2#187]
由于 server 提供的接口入参中有一个 java 定义的枚举，所以我在 client 端参照 dubbo-go 的 demo 注册了对应枚举，但是在 packRequest 的过程中 getArgType 返回了 "" 导致 error
2020-05-14T18:43:10.068+0800    ERROR   runtime/asm_amd64.s:1357        {client:TCP_CLIENT:2:xxxx<->xxxx}, [session.handleLoop] = error:cat not get arg 1 type

![image](https://user-images.githubusercontent.com/34745530/81925057-8e590d80-9612-11ea-85a1-238a3d905f05.png)

**Comment by panyfun** [comment]
github.com/apache/dubbo-go v1.4.1
github.com/apache/dubbo-go-hessian2 v1.5.0

**Comment by pantianying** [comment]
已经在本地复现 正在解决中
