### ISSUE TITLE
Add: go struct for  jdk8 time

### ISSUE THREAD

**Issue by AlexStocks** [apache/dubbo-go-hessian2#193]
**What would you like to be added**:

Add go structs for the following time classes in jdk8:

- java.time.OffsetDateTime
- java.time.ZoneOffset
- java.time.OffsetTime
- java.time.ZoneDateTime 

- java.time.Year
- java.time.YearMonth
- java.time.MonthDay

- java.time.Instant
- java.time.Duration
- java.time.Period

- java.time.LocalTime
- java.time.LocalDate
- java.time.LocalDateTime

- java.sql.Date
- java.sql.Time
- java.sql.Timestamp

**Why is this needed**:

these classes are very popular in jdk8.

**Comment by AlexStocks** [comment]
to  [willson-chen](github.com/willson-chen)

**Comment by wongoo** [comment]
suggest add java clas support in other project， eg：
- dubbogo/hessian-java-ext-basic
- dubbogo/hessian-java-ext-exception
- dubbogo/hessian-java-ext-time

@AlexStocks @fangyincheng @hxmhlt

**Comment by AlexStocks** [comment]
> suggest add java clas support in other project， eg：
> 
> * dubbogo/hessian-java-ext-basic
> * dubbogo/hessian-java-ext-exception
> * dubbogo/hessian-java-ext-time
> 
> @AlexStocks @fangyincheng @hxmhlt

why? If so, we should move the exception too.

**Comment by wongoo** [comment]
it seems there are going to add more and more java classes to support

**Comment by AlexStocks** [comment]
> it seems there are going to add more and more java classes to support

agree with u. firstly, we can move the exception outside. And then we add the other java classes.

**Comment by wongoo** [comment]
> > it seems there are going to add more and more java classes to support
> 
> agree with u. firstly, we can move the exception outside. And then we add the other java classes.

I have changed my opinion, moving the exception outside need user to change the source code. so adding the time class mapping in this project may be better, but not load it default, asking user to init to load when required, because it will not be used for most users and projects.

**Comment by AlexStocks** [comment]
> > > it seems there are going to add more and more java classes to support
> > 
> > 
> > agree with u. firstly, we can move the exception outside. And then we add the other java classes.
> 
> I have changed my opinion, moving the exception outside need user to change the source code. so adding the time class mapping in this project may be better, but not load it default, asking user to init to load when required, because it will not be used for most users and projects.

ok.
