### ISSUE TITLE
go-hessian2报错 error:decObject illegal object type tag:121

### ISSUE THREAD

**Issue by jjhewlett** [apache/dubbo-go-hessian2#220]
go-hessian2报错 error:decObject illegal object type tag:121

我是Java服务端，dubbo-go是客户端。
现在Data是java下发的一个List，list里每一个元素，都是实体对象
下发单个没问题，下发list的就go-hessian2抛异常

hessian.RegisterPOJO(&ResponseData{})
type ResponseData struct {
Code string
Msg string
Data interface{}
}

**Comment by wongoo** [comment]
there should be a `JavaClassName()` func for the struct.

**Comment by jjhewlett** [comment]
@wongoo  我都已经设置好了的。
GetOrder这个方法返回的是一个order list
GetOrderOne 返回的是一个order object
响应的数据结构都是ResponseData
![image](https://user-images.githubusercontent.com/69667512/90461058-e8003500-e137-11ea-9152-0368589ce1f1.png)

**Comment by wongoo** [comment]
@jjhewlett  more details needed, include java object definition, java test data, code sample.  And I guess, u only register ResponseData, but not for order object. u need register all objects.

**Comment by jjhewlett** [comment]
@wongoo 这个是JAVA服务端的代码，现在getOrderOne是可以正常返回的。
![image](https://user-images.githubusercontent.com/69667512/90461984-59d97e00-e13a-11ea-8481-94eb3bbc5c9c.png)

**Comment by jjhewlett** [comment]
@wongoo  我在Go语言的客户端已经注册了order的结构体了

**Comment by wongoo** [comment]
glad to hear that, and u can post how that you resolve your problem, maybe it's useful for others.

**Comment by jjhewlett** [comment]
@wongoo 
目前还没有解决这个问题，我目前也很苦恼
在JAVA服务层，我的DATA是个泛型。
我尝试过go客户端的response data改成[]interface{},但是改成这样我的详情就直接抛相同的异常了。

**Comment by wongoo** [comment]
@jjhewlett u can create a test case so that we can work on it, ref the example as follow:

https://github.com/apache/dubbo-go-hessian2/blob/9e91fc9a7de335e427999bd3cd9cd60ef0304169/test_hessian/src/main/java/test/TestCustomReply.java#L428

https://github.com/apache/dubbo-go-hessian2/blob/9e91fc9a7de335e427999bd3cd9cd60ef0304169/object_test.go#L767

**Comment by jjhewlett** [comment]
@wongoo 好的，我先看下测试用例。真的万分感谢。

**Comment by jjhewlett** [comment]
@wongoo 您好。看了下pojo.go的代码，
好像是一个JavaClassName 对应一个goName。
不知道可不可以实现多个JavaClassName 对应一个goName呢

**Comment by wongoo** [comment]
not support now, u can create a new struct extending the exist one and overwrite the JavaClassName func

**Comment by jjhewlett** [comment]
OK,我试下继承重写。要是GO支持泛型就没那么麻烦了。

**Comment by jjhewlett** [comment]
@wongoo 万分感谢

**Comment by jjhewlett** [comment]
@wongoo 你好，
服务端返回的是一个map.
map有2个key,一个key是int，一个key是list
该如何定义。才能够正常解析。

**Comment by AlexStocks** [comment]
@jjhewlett  why u define so complicated map？

**Comment by wongoo** [comment]
@jjhewlett  你最好按照上面我给你的例子写一个test case，把问题模拟出来，这样才好分析问题出在哪里。 比如这个issue https://github.com/apache/dubbo-go-hessian2/issues/214 就是一个很好的例子。

**Comment by jjhewlett** [comment]
@wongoo 目前data没有被解析出来
![image](https://user-images.githubusercontent.com/69667512/90496512-801e0e80-e178-11ea-82ae-7b1288d3f1fd.png)

import (
	hessian "github.com/apache/dubbo-go-hessian2"
	"fmt"
)

type ResponseData struct {
	Code string
	Msg  string
	Data map[string]interface{}
}


func (ResponseData) JavaClassName() string {
	return "com.example.dubbo_tools.domain.ResponseData"
}

func main() {
	res := &ResponseData{}
	res.Code = "0000"
	res.Msg = "成功"

	list := []string{"A","B","C"}
	data := map[string]interface{}{
		"count" : 1,
		"data"  : list,
	}
	res.Data = data

	e := hessian.NewEncoder()
	err := e.Encode(res)
	if err != nil {
		panic(err)
	}
	bytes := e.Buffer()
	decoder := hessian.NewDecoder(bytes)
	decode, err := decoder.Decode()
	if err != nil {
		panic(err)
	}
	fmt.Println(decode)
}

**Comment by jjhewlett** [comment]
非常感谢 @wongoo @AlexStocks 这两位大神的技术支持。现在已经和JAVA端通信成功了。
因为Golang语法不支持泛型。已经将代码改成如下
![image](https://user-images.githubusercontent.com/69667512/90608613-73abbb80-e235-11ea-91e9-85da1ffecd4d.png)
返回结果：
![image](https://user-images.githubusercontent.com/69667512/90608775-a8b80e00-e235-11ea-807b-71603f35cfab.png)

**Comment by AlexStocks** [comment]
@jjhewlett u r welcome. Would u help us to register ur com/org info into https://github.com/apache/dubbo-go/issues/2? thank u so much.

**Comment by jjhewlett** [comment]
@AlexStocks 非常感谢您的邀请，目前我们公司还是以JAVA为主。以后我有新的机会的时候会尝试dubbo-go。

**Comment by milerL** [comment]
> @AlexStocks 非常感谢您的邀请，目前我们公司还是以JAVA为主。以后我有新的机会的时候会尝试dubbo-go。

go的客户端 strcut 看着好奇怪啊。。能看一下你的ResponseData Struct 吗

**Comment by milerL** [comment]
@jjhewlett  打扰了 问一下你们有没有遇到过 
外面用Response包了一层  然后Response里面有个result 字段返回  结构体或者int 这种情况
