### ISSUE TITLE
有关于java server端 泛型的问题

### ISSUE THREAD

**Issue by milerL** [apache/dubbo-go-hessian2#238]
java server端
![image](https://user-images.githubusercontent.com/26897689/95649158-ae7ff080-0b0e-11eb-97ba-b0e129beabc8.png)
![image](https://user-images.githubusercontent.com/26897689/95649167-bb9cdf80-0b0e-11eb-9c68-60e5d92f1710.png)
使用response包了一层

这是go版本 写的response
![image](https://user-images.githubusercontent.com/26897689/95649290-601f2180-0b0f-11eb-9613-6507784c9116.png)
我打算用 interface{} 接收所有数据 不管是 int还是string 还是数组

我看了 #220 的问题
![image](https://user-images.githubusercontent.com/26897689/95649335-93fa4700-0b0f-11eb-8f67-7afd7bca1359.png)
注册时 用的RegisterPOJOs
接收一个 结构体时 没什么问题 但是接收一个int64 时 就报错了

![image](https://user-images.githubusercontent.com/26897689/95649366-be4c0480-0b0f-11eb-82cf-164aa20e7e10.png)

请问我该怎么做才能接收所有类型的数据

**Comment by milerL** [comment]
还有另外一个services  同样返回 Response<UserModel>
无法解析

但是fandById 却没有问题

**Comment by milerL** [comment]
这是我service struct
![image](https://user-images.githubusercontent.com/26897689/95650953-6c0fe100-0b19-11eb-812c-7f4ac6e6591c.png)

**Comment by wongoo** [comment]
@milerL  pls try the master branch and check whether it resolves your problem

**Comment by milerL** [comment]
@wongoo 解决了

有个小问题，如果 java server 有个字段  age是Integer   然后java 传了一个 age:null   这样是不是无法解析

**Comment by wongoo** [comment]
@milerL  Integer is not supported now , ref https://github.com/hessian-group/hessian-type-mapping

**Comment by milerL** [comment]
@wongoo 感谢
