### ISSUE TITLE
hard coded credential?

### ISSUE THREAD

**Issue by asottile** [apache/dubbo-go-hessian2#246]
https://github.com/apache/dubbo-go-hessian2/blob/07e93979195dcefa9e5c590409cc6d9886cec7cb/.github/workflows/github-actions.yml#L26-L27

Is this intentionally public?

**Comment by AlexStocks** [comment]
it is out of date and has no usage. has no security affect.

**Comment by asottile** [comment]
cool so that token is expired, perfect
