### ISSUE TITLE
解析java 返回的dubbo数据偶尔会报not enough buf

### ISSUE THREAD

**Issue by jack15083** [apache/dubbo-go-hessian2#248]
非常奇怪的报错找不到原因

{"level":"error","msg":"session-closed, [session.handlePackage] error:not enough buf\ngithub.com/apache/dubbo-go-hessian2.init\n\t/home/gopath/pkg/mod/github.com/apache/dubbo-go-hessian2@v1.6.2/decode.go:44\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5625\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5620\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5620\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5620\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5620\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:191\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\ngithub.com/apache/dubbo-go-hessian2.(*Decoder).readUntypedList\n\t/home/gopath/pkg/mod/github.com/apache/dubbo-go-hessian2@v1.6.2/list.go:413\ngithub.com/apache/dubbo-go-hessian2.(*Decoder).decList\n\t/home/gopath/pkg/mod/github.com/apache/dubbo-go-hessian2@v1.6.2/list.go:286\ngithub.com/apache/dubbo-go-hessian2.(*Decoder).DecodeValue\n\t/home/gopath/pkg/mod/github.com/apache/dubbo-go-hessian2@v1.6.2/decode.go:253\ngithub.com/apache/dubbo-go-hessian2.(*Decoder).Decode\n\t/home/gopath/pkg/mod/github.com/apache/dubbo-go-hessian2@v1.6.2/decode.go:189\ngithub.com/apache/dubbo-go-hessian2.(*Decoder).decMap\n\t/home/gopath/pkg/mod/github.com/apache/dubbo-go-hessian2@v1.6.2/map.go:310\ngithub.com/apache/dubbo-go-hessian2.(*Decoder).DecodeValue\n\t/home/gopath/pkg/mod/github.com/apache/dubbo-go-hessian2@v1.6.2/decode.go:256\ngithub.com/apache/dubbo-go-hessian2.(*Decoder).Decode\n\t/home/gopath/pkg/mod/github.com/apache/dubbo-go-hessian2@v1.6.2/decode.go:189\ngithub.com/apache/dubbo-go-hessian2.unpackResponseBody\n\t/home/gopath/pkg/mod/github.com/apache/dubbo-go-hessian2@v1.6.2/response.go:194\ngithub.com/apache/dubbo-go-hessian2.(*HessianCodec).ReadBody\n\t/home/gopath/pkg/mod/github.com/apache/dubbo-go-hessian2@v1.6.2/hessian.go:211\ngithub.com/apache/dubbo-go/protocol/dubbo.(*DubboPackage).Unmarshal\n\t/home/gopath/pkg/mod/github.com/jack15083/dubbo-go@v1.5.17/protocol/dubbo/codec.go:121\ngithub.com/apache/dubbo-go/protocol/dubbo.(*RpcClientPackageHandler).Read\n\t/home/gopath/pkg/mod/github.com/jack15083/dubbo-go@v1.5.17/protocol/dubbo/readwriter.go:56\ngithub.com/apache/dubbo-getty.(*session).handleTCPPackage\n\t/home/gopath/pkg/mod/github.com/apache/dubbo-getty@v1.3.10/session.go:775\ngithub.com/apache/dubbo-getty.(*session).handlePackage\n\t/home/gopath/pkg/mod/github.com/apache/dubbo-getty@v1.3.10/session.go:697\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\ngithub.com/apache/dubbo-go-hessian2.unpackResponseBody\n\t/home/gopath/pkg/mod/github.com/apache/dubbo-go-hessian2@v1.6.2/response.go:196\ngithub.com/apache/dubbo-go-hessian2.(*HessianCodec).ReadBody\n\t/home/gopath/pkg/mod/github.com/apache/dubbo-go-hessian2@v1.6.2/hessian.go:211\ngithub.com/apache/dubbo-go/protocol/dubbo.(*DubboPackage).Unmarshal\n\t/home/gopath/pkg/mod/github.com/jack15083/dubbo-go@v1.5.17/protocol/dubbo/codec.go:121\ngithub.com/apache/dubbo-go/protocol/dubbo.(*RpcClientPackageHandler).Read\n\t/home/gopath/pkg/mod/github.com/jack15083/dubbo-go@v1.5.17/protocol/dubbo/readwriter.go:56\ngithub.com/apache/dubbo-getty.(*session).handleTCPPackage\n\t/home/gopath/pkg/mod/github.com/apache/dubbo-getty@v1.3.10/session.go:775\ngithub.com/apache/dubbo-getty.(*session).handlePackage\n\t/home/gopath/pkg/mod/github.com/apache/dubbo-getty@v1.3.10/session.go:697\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\ngithub.com/apache/dubbo-go-hessian2.(*HessianCodec).ReadBody\n\t/home/gopath/pkg/mod/github.com/apache/dubbo-go-hessian2@v1.6.2/hessian.go:212\ngithub.com/apache/dubbo-go/protocol/dubbo.(*DubboPackage).Unmarshal\n\t/home/gopath/pkg/mod/github.com/jack15083/dubbo-go@v1.5.17/protocol/dubbo/codec.go:121\ngithub.com/apache/dubbo-go/protocol/dubbo.(*RpcClientPackageHandler).Read\n\t/home/gopath/pkg/mod/github.com/jack15083/dubbo-go@v1.5.17/protocol/dubbo/readwriter.go:56\ngithub.com/apache/dubbo-getty.(*session).handleTCPPackage\n\t/home/gopath/pkg/mod/github.com/apache/dubbo-getty@v1.3.10/session.go:775\ngithub.com/apache/dubbo-getty.(*session).handlePackage\n\t/home/gopath/pkg/mod/github.com/apache/dubbo-getty@v1.3.10/session.go:697\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\ngithub.com/apache/dubbo-go/protocol/dubbo.(*DubboPackage).Unmarshal\n\t/home/gopath/pkg/mod/github.com/jack15083/dubbo-go@v1.5.17/protocol/dubbo/codec.go:122\ngithub.com/apache/dubbo-go/protocol/dubbo.(*RpcClientPackageHandler).Read\n\t/home/gopath/pkg/mod/github.com/jack15083/dubbo-go@v1.5.17/protocol/dubbo/readwriter.go:56\ngithub.com/apache/dubbo-getty.(*session).handleTCPPackage\n\t/home/gopath/pkg/mod/github.com/apache/dubbo-getty@v1.3.10/session.go:775\ngithub.com/apache/dubbo-getty.(*session).handlePackage\n\t/home/gopath/pkg/mod/github.com/apache/dubbo-getty@v1.3.10/session.go:697\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\ngithub.com/apache/dubbo-go/protocol/dubbo.(*RpcClientPackageHandler).Read\n\t/home/gopath/pkg/mod/github.com/jack15083/dubbo-go@v1.5.17/protocol/dubbo/readwriter.go:65\ngithub.com/apache/dubbo-getty.(*session).handleTCPPackage\n\t/home/gopath/pkg/mod/github.com/apache/dubbo-getty@v1.3.10/session.go:775\ngithub.com/apache/dubbo-getty.(*session).handlePackage\n\t/home/gopath/pkg/mod/github.com/apache/dubbo-getty@v1.3.10/session.go:697\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\ngithub.com/apache/dubbo-getty.(*session).handleTCPPackage\n\t/home/gopath/pkg/mod/github.com/apache/dubbo-getty@v1.3.10/session.go:802\ngithub.com/apache/dubbo-getty.(*session).handlePackage\n\t/home/gopath/pkg/mod/github.com/apache/dubbo-getty@v1.3.10/session.go:697\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\ngithub.com/apache/dubbo-getty.(*session).handlePackage.func1\n\t/home/gopath/pkg/mod/github.com/apache/dubbo-getty@v1.3.10/session.go:683\ngithub.com/apache/dubbo-getty.(*session).handlePackage\n\t/home/gopath/pkg/mod/github.com/apache/dubbo-getty@v1.3.10/session.go:705\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374","time":"2020-12-17 10:30:38.581"}

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by wongoo** [comment]
@jack15083  there are many bug fix , see release note https://github.com/apache/dubbo-go-hessian2/blob/1.8/CHANGE.md, do u try the latest version?

**Comment by wongoo** [comment]
@jack15083  try to find the data causing this issue, so that we can test and fix it.

**Comment by jack15083** [comment]
屏蔽掉这个检查就好了，貌似解析日期也没有问题，大佬想一下是啥原因
![image](https://user-images.githubusercontent.com/2142066/102450336-1869c880-4071-11eb-8781-aec9260bb6d6.png)

**Comment by wongoo** [comment]
@jack15083 comment this may cause decoding wrong date value, can you debug to get the object data?

**Comment by jack15083** [comment]
要那个对象的数据啊

**Comment by jack15083** [comment]
> @jack15083 comment this may cause decoding wrong date value, can you debug to get the object data?

需要debug哪个对象的数据啊

**Comment by jack15083** [comment]
> @jack15083 there are many bug fix , see release note https://github.com/apache/dubbo-go-hessian2/blob/1.8/CHANGE.md, do u try the latest version?

1.8.0试过了也有这个问题

**Comment by wongoo** [comment]
to get the business object which causing this issue,  try to recreate this issue:
1. create a custom reply in java, eg: https://github.com/apache/dubbo-go-hessian2/blob/bb72ebc87514ed3bc1aa7408d4e201316a3e09fa/test_hessian/src/main/java/test/TestCustomReply.java#L433
2. test the java output, eg: https://github.com/apache/dubbo-go-hessian2/blob/bb72ebc87514ed3bc1aa7408d4e201316a3e09fa/object_test.go#L765
