### ISSUE TITLE
Map里面的decimal类型无法解析

### ISSUE THREAD

**Issue by wenxuwan** [apache/dubbo-go-hessian2#259]
**What happened**:
Java测，如果Map里面塞入decimal类型，解析会失败。

**What you expected to happen**:
Java测，如果Map里面塞入decimal类型，可以正常解析。

**How to reproduce it (as minimally and precisely as possible)**:

如下图所示，如果在Map中塞入一个decimal类型，dubbo-go这边将会解析失败。

![image](https://user-images.githubusercontent.com/11661906/110056506-eaf00980-7d99-11eb-8a5a-8473eb2f4dba.png)

![image](https://user-images.githubusercontent.com/11661906/110056522-f4797180-7d99-11eb-8c57-a9eaa44f4a59.png)

**Comment by wongoo** [comment]
@fangyincheng  pls follow this issue ~

**Comment by wongoo** [comment]
@wenxuwan I have found the cause of this issue,  I will try to fix it in this weekend.

**Comment by wenxuwan** [comment]
> @wenxuwan I have found the cause of this issue, I will try to fix it in this weekend.

Thank u man
