### ISSUE TITLE
dubbo-java 调用 dubbo-go方法，如果方法返回值为 基本类型，java侧无法解析

### ISSUE THREAD

**Issue by luky116** [apache/dubbo-go-hessian2#291]
**What happened**:
java-dubbo-client 调用 Dubbo-go-server的方法，结果值为int类型，go把这个值的类型转成了 J 作为返回值。但是java-client没办法解析这个类型

<img width="1050" alt="1637428671264_41DC60BB-090A-4A12-91AF-B3EB7E2B2AEB" src="https://user-images.githubusercontent.com/38887641/142748713-70f60558-e248-48d2-adb5-aedcdcc3e9c0.png">

这是java侧的效果：

![1637428671267_A00F0138-F775-400A-AAA9-247440E1267B](https://user-images.githubusercontent.com/38887641/142748946-965716f8-91e5-42d9-95d9-9700a3d2efe7.png)
**What you expected to happen**:
希望java-client能识别 J 为int类型，并解析出response

**How to reproduce it (as minimally and precisely as possible)**:
可以参考dubbogo-sample这个例子，能复现问题：
https://github.com/luky116/dubbo-go-samples/tree/fix-tpcTripleHessian2/rpc/triple/hessian2

**Anything else we need to know?**:
no

**Comment by sanxun0325** [comment]
@luky116 已经定位到问题的根因，只有tri协议时才会出现,我会在dubbo/grpc-go中提交pr修复它，这个问题本质和hessian2无关

**Comment by wongoo** [comment]
@sanxun0325 pls add a link ref to the pr submitted in dubbo-go.
