### ISSUE TITLE
go调用java，返回值为枚举类型，会报错

### ISSUE THREAD

**Issue by luky116** [apache/dubbo-go-hessian2#294]
go-client调用java-server，返回值为枚举类型，go侧报错了。这个有同学遇过吗？

![image](https://user-images.githubusercontent.com/38887641/143768354-cfb01278-63f0-4466-a3c5-6032963034fc.png)

**Comment by wongoo** [comment]
`gender, err := userProvider.GetGender(context.TODO(), 1)` 这里的最后一个参1 ，应该用 MAN/WOMAN 吧？

**Comment by luky116** [comment]
> `gender, err := userProvider.GetGender(context.TODO(), 1)` 这里的最后一个参1 ，应该用 MAN/WOMAN 吧？

参数定义的是int，返回值是枚举值。
java-server端是可以正常收到参数并处理返回的，但是go-client端无法解析返回的结果。
![image](https://user-images.githubusercontent.com/38887641/144339798-00b3338e-70b2-42ae-8538-452d0b994ffb.png)
