### ISSUE TITLE
Decode 阶段，'B' (byte) 标会被解析为 int32

### ISSUE THREAD

**Issue by LaurenceLiZhixin** [apache/dubbo-go-hessian2#310]
这一行负责解析为int32
https://github.com/apache/dubbo-go-hessian2/blob/c18594c8ecd05dbd953d68ab1fab03d4a1d6c6e5/decode.go#L273
位置位于解析byte之前：
https://github.com/apache/dubbo-go-hessian2/blob/c18594c8ecd05dbd953d68ab1fab03d4a1d6c6e5/decode.go#L295

而'B' byte 标会优先进入int32的处理分支，被解析为int32，因为'B' == 0x91 ，符合int32的第一个条件。

**Comment by wongoo** [comment]
@LaurenceLiZhixin can u provide a demo for this issue?

**Comment by wongoo** [comment]
@LaurenceLiZhixin  `B` is 0x42
