### ISSUE TITLE
go-client调用Java-serve 当java接口参数类型Integer等包装类时go报错找不到服务

### ISSUE THREAD

**Issue by vaeWl** [apache/dubbo-go-hessian2#345]
go代码片段:
<img width="1066" alt="图片" src="https://user-images.githubusercontent.com/124427268/216772104-3b7f2772-87ef-4540-9ed5-aa96547e7481.png">

java代码片段:
<img width="547" alt="图片" src="https://user-images.githubusercontent.com/124427268/216772167-82883314-f352-4640-b477-cf2de60ca4fe.png">

报错信息:
<img width="1382" alt="图片" src="https://user-images.githubusercontent.com/124427268/216772142-b8f93e78-5b46-4894-9dae-2e383aa2b187.png">

但是如果java的service的接口为非包装类时是正常的:
<img width="460" alt="图片" src="https://user-images.githubusercontent.com/124427268/216772445-cb060912-e304-4ef4-89f4-a6e29871b08e.png">
<img width="553" alt="图片" src="https://user-images.githubusercontent.com/124427268/216772457-425132fc-babb-41b4-8802-266ee994c1d0.png">

<img width="1007" alt="图片" src="https://user-images.githubusercontent.com/124427268/216772484-0c626229-46cb-4401-baf7-ba951c6062c5.png">

非包装类正常返回:
<img width="428" alt="图片" src="https://user-images.githubusercontent.com/124427268/216772525-80a244a7-5fdb-442e-82b0-d98f3e32d9cd.png">

**Comment by tiltwind** [comment]
ref: https://github.com/apache/dubbo-go-hessian2/issues/349

**Comment by tiltwind** [comment]
@vaeWl  the java wrapper is supported now, you can upgrade it like https://github.com/apache/dubbo-go/pull/2222. 
Pls tell us whether it does work or not, thanks!
