### ISSUE TITLE
时间encode越界

### ISSUE THREAD

**Issue by Penglq** [apache/dubbo-go-hessian2#348]
**What happened**:
dubbo-go一个原始日期为：2296-11-23 16:09:26.311 的值，java那边收到的是另一个值，是因为hessian的类型不对导致越界了吗
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by tiltwind** [comment]
@Penglq can u submit a unit test to simulate the unexpected case, ref  https://github.com/apache/dubbo-go-hessian2/blob/4820c033e874cf8bdbc6e1aea0c3c4ce0d63ceea/date_test.go#L96

**Comment by tiltwind** [comment]
@Penglq  the hessian2 uses the api `time.UnixNano()`, but the year `2914` overflows for int64 for nanoseconds.
From golang 1.17, it supports `time.UnixMilli()` api, which will fix this issue.

But now the go version of the hessian ci used is 1.13, maybe we needs to upgrade the go version now. 
How do u think？@AlexStocks

```go
// UnixNano returns t as a Unix time, the number of nanoseconds elapsed
// since January 1, 1970 UTC. The result is undefined if the Unix time
// in nanoseconds cannot be represented by an int64 (a date before the year
// 1678 or after 2262). Note that this means the result of calling UnixNano
// on the zero Time is undefined. The result does not depend on the
// location associated with t.
func (t Time) UnixNano() int64 {
	return (t.unixSec())*1e9 + int64(t.nsec())
}
```

**Comment by tiltwind** [comment]
currently, dubbo-go uses go v1.15, ref https://github.com/apache/dubbo-go/blob/master/.github/workflows/github-actions.yml

**Comment by ilaotan** [comment]
支持升版本
