### ISSUE TITLE
Ftr:  We should allow the passed []struct type in the argument instead of []interface{}

### ISSUE THREAD

**Issue by hxmhlt** [apache/dubbo-go-hessian2#52]
**What would you like to be added**:
We should allow the passed []struct type in the argument instead of []interface{}.

**Why is this needed**:

Developers may feel very confused and have a bad development experience because of dubbogo's limitation.

**Comment by wongoo** [comment]
hessian2 supports encoding slice/array type, there is [an example](https://github.com/dubbogo/hessian2/blob/c432dcada9eab283abc851c7f65760f18a0377c6/hessian_test.go#L96). Could u pls to provide an example about this issue?
@fangyincheng @hxmhlt

**Comment by fangyincheng** [comment]
`doTestResponse(t, PackageResponse, Response_OK, []Case{A: "a", B: 1}, &[]Case{}, nil)`
As above, is it already supported?

**Comment by wongoo** [comment]
@hxmhlt have u tried it again?

**Comment by wongoo** [comment]
close for no progress
