### ISSUE TITLE
about Generic$invoke

### ISSUE THREAD

**Issue by pantianying** [apache/dubbo-go-hessian2#84]
抱歉英文不好，就用中文了。以上是对泛化调用的需求记录；

**目标：实现goclient to javaserver 的泛化调用**

以下是实现的探讨，我入门java不到一个月，肯定会有不对的地方，欢迎指出，也希望有java老鸟帮忙看看，十分感谢。

所谓泛化调用是指客户端拿不到服务端的具体类的情况（在go的客户端表现为没有写死的providerserver接口和pojo定义），java的dubbo框架已经有了这个功能，这个功能对于dubbo接口网关类服务的实现是必不可少的。

**看了源码我自我以为的java的实现：**
java provider端有这样一个interface
![image](https://user-images.githubusercontent.com/20589945/60002638-95de9380-969b-11e9-90e6-d5bbaaa6234e.png)
所有的客户端都调用该接口的$invoke进行访问，将原来的方法、参数、类型都作为请求参数
（我自己测试过，确实能够调通，但由于hessian2[的这个问题](https://github.com/dubbogo/hessian2/issues/76)，没有进入下一步的测试）
如图
![image](https://user-images.githubusercontent.com/20589945/60003397-2ec1de80-969d-11e9-9265-ae94372b4a64.png)

客户端在没有注册pojo是如何解析返回的数据的。看了源码，invoke方法会将pojo转换成map返回，map中的所有元素都是基本类型，java客户端直接解析map即可，所以目前来看，如果hessain2能够支持不定深度map、数组的解析，应该就可以支持泛化调用。

**Comment by pantianying** [comment]
客户端的生成源码在com.alibaba.dubbo.config.ReferenceConfig

调用ReferenceConfig.get()获取服务端泛化接口，源码有点多就不贴了

**Comment by pantianying** [comment]
贴一下使用的java代码吧
`    public static Object invokeDubbo(UrlPathInfo pathInfo, Object[] parameterObjects) {
        ReferenceConfig<GenericService> referenceConfig = null;
        try {
            referenceConfig = referenceConfigLoadingCache.get(pathInfo);
        } catch (ExecutionException e) {
            logger.error("get referenceConfig from jvm cache has error", e);
        }
        if (referenceConfig == null) {
            referenceConfig = buildReferenceConfig(pathInfo);
            if (referenceConfig != null) {
                referenceConfigLoadingCache.refresh(pathInfo);
            }
        }

        GenericService genericService = referenceConfig.get();
        String[] paramTypes = pathInfo.getParameterTypes();
        RpcContext.getContext().setAttachment(HighwayConstants.HIGHWAY_CONSUMER_NAME, HighwayConstants.HIGHWAY_CONSUMER_NAME);
        Object returnValue = genericService.$invoke(pathInfo.getMethodName(), paramTypes, parameterObjects);
        //void 返回为null
        return returnValue;
    }`

**Comment by wongoo** [comment]
和 @pantianying 沟通，目前golang hessian2不支持反序列化未定义的pojo数据为map，而java是可以的，需要调研的是java的实现机制是如何？ 是不是针对泛化的请求，java server端会用map的方式来序列化返回数据？ 如果对java有研究的，请分享一下！

**Comment by pantianying** [comment]
@wongoo 
我自认为 将pojo转化为map这个java的provider已经做了，返回到客户端就是map的序列化，客户端只要能够解析map就可以了

**Comment by pantianying** [comment]
@wongoo @fangyincheng 

大家好，根据阅读源码和@fangyincheng一起测试，pojo到map的步骤确认是在java的provder实现了，目前goclient端利用如下的interface定义，可以调通java provider端的泛化调用。
![image](https://user-images.githubusercontent.com/20589945/60417059-0b091600-9c12-11e9-98d1-55accd450a85.png)
![image](https://user-images.githubusercontent.com/20589945/60417356-ce89ea00-9c12-11e9-8b7f-bf306777e74c.png)

因为java服务端只把pojo转成了map，客户端目前还需要区别pojo数组还是单个pojo。这个希望能通过一个interface{} 接受所有的返回。

这个实现需要两位评估。
