### ISSUE TITLE
can't decode null java date

### ISSUE THREAD

**Issue by wongoo** [apache/dubbo-go-hessian2#90]
**What happened**:
link to：  https://github.com/apache/dubbo-go/issues/105

**What you expected to happen**:
enable to decode null java date object

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Comment by aliiohs** [comment]
i will try it.

**Comment by wongoo** [comment]
@aliiohs first u must what's the encode result of null java date in java, then encode it to a zero go date, eg `var _zeroDate time.Time`. pls let me know for any question.

**Comment by lovepoem** [comment]
I will have a try

**Comment by lovepoem** [comment]
/**java

    /**
     * Writes a null value to the stream.
     * The null will be written with the following syntax
     * <p>
     * <code><pre>
     * N
     * </pre></code>
     *
     * @param value the string value to write.
     */
    @Override
    public void writeNull()
            throws IOException {
        os.write('N');
    }
**/

when a field is null , the stream is `N`

**Comment by lovepoem** [comment]
>  then encode it to a zero go date

What is  zero go date, how to produce it ?  @wongoo

**Comment by wongoo** [comment]
@lovepoem a definition without assigment of time.Time is a zero go date , eg `var _zeroDate time.Time`
